services:
  # 1. API Gateway / Load Balancer (Entry Point)
  nginx:
    image: nginx:stable-alpine
    container_name: phu-nginx
    restart: always
    ports:
      # Expose Nginx on port 5000 to the host
      - "5000:80" 
    volumes:
      # Mount the corrected nginx.conf
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app-core
      - app-realtime
      - redis # Redis is often a dependency for the app services
      
  # 2. Application Server (Core Business Logic, Handles /login, /api/inventory, etc.)
  app-core:
    build: . 
    container_name: phu-app-core
    environment:
      - FLASK_APP=app.py
      - MONGO_URI=mongodb://admin:password@mongodb:27017/PokemonNexusDB?authSource=admin
      - SECRET_KEY=your_strong_and_secret_key_for_flashing
      - SESSION_TYPE=redis
      - SESSION_REDIS=redis://redis:6379/1 
    depends_on:
      - mongodb
      - redis
    volumes:
      - ./web:/app 
    # Use Gunicorn for standard HTTP requests
    command: gunicorn -w 4 -b 0.0.0.0:5000 app:app 

  # 3. Real-Time/Battle Server (Handles WebSockets/SocketIO)
  app-realtime:
    build: . 
    container_name: phu-app-realtime
    environment:
      - FLASK_APP=app.py
      - MONGO_URI=mongodb://admin:password@mongodb:27017/PokemonNexusDB?authSource=admin
      - SECRET_KEY=your_strong_and_secret_key_for_flashing
      - SESSION_TYPE=redis
      - SESSION_REDIS=redis://redis:6379/1 
    depends_on:
      - mongodb
      - redis
    volumes:
      - ./web:/app 
    # Eventlet worker with explicit timeout settings
    command: gunicorn -k eventlet -w 1 --bind 0.0.0.0:5001 --timeout 300 --keep-alive 65 --log-level debug app:app

  # 4. Task Queue Broker (Redis)
  redis:
    image: redis:latest
    container_name: phu-redis
    restart: always
    ports:
      - "6379:6379"
    command: redis-server --bind 0.0.0.0
    volumes:
      - phu-redis-volume:/data

  # 5. Database (MongoDB)
  mongodb:
    image: mongo:latest
    container_name: phu-mongodb
    restart: always
    ports:
      - "27017:27017" 
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - phu-mongo-volume:/data/db

volumes:
  phu-mongo-volume:
  phu-redis-volume: