# Use a lightweight Python base image
FROM python:3.11-slim

# Set the working directory
WORKDIR /app

# Copy the requirements file and install dependencies
COPY requirements-test.txt .
RUN pip install --no-cache-dir -r requirements-test.txt

# Copy the test scripts
COPY locustfile.py .
COPY seed_db.py .

# Command to run the seeder (will be overridden in docker-compose for the test run)
CMD ["python", "seed_db.py"]
