version: '3.8'

services:
  web:
    build: .
    ports:
      # Host:Container
      - "5000:5000"
    environment:
      # Flask app environment variables
      - FLASK_APP=app.py
      - FLASK_ENV=development
      # Database Connection String for Flask (connects to the 'mongodb' service)
      - MONGO_URI=mongodb://admin:password@mongodb:27017/PokemonNexusDB?authSource=admin
      - SECRET_KEY=your_strong_and_secret_key_for_flashing
    depends_on:
      - mongodb # Ensures the 'mongodb' service starts before 'web'
    # volume mounts src code and watch for changes in development
    volumes:
      - ./web:/app
    develop:
      watch:
        - action: sync+restart
          path: ./web/
          target: /app/

  mongodb:
    image: mongo:latest
    container_name: phu-mongodb
    restart: always
    ports:
      # Host:Container
      - "27017:27017" 
    environment:
      # --- Root User for Initial Authentication (Required by the official image) ---
      # This user has admin rights to the entire instance.
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      # Persist the database data
      - phu-mongo-volume:/data/db

volumes:
  phu-mongo-volume: